version: '3.9'
x-customer-integrations:
  logs:
  metrics:

x-omnistrate-load-balancer:
  https:
    - name: frontend
      description: L7 Load Balancer for Web
      paths:
        - associatedResourceKey: web
          path: /
          backendPort: 3000

services:
  web:
    image: nginxdemos/hello:0.4
    ports:
      - '3000:3000'

  worker:
    image: busybox
    command: ['sh', '-c', 'while true; do echo Working...; sleep 10; done']
