version: '3.9'
x-customer-integrations:
  logs:
  metrics:

x-omnistrate-load-balancer:
  https:
    - name: frontend
      description: L7 Load Balancer to expose the controller Web UI
      paths:
        - associatedResourceKey: controller
          path: /
          backendPort: 3000

services:

  controller:
    depends_on:
      - worker
    image: ghcr.io/omnistrate-community/custom-auto-scaling-example:0.0.2
    ports:
      - '3000:3000'
    environment:
      - AUTOSCALER_COOLDOWN=300
      - AUTOSCALER_TARGET_RESOURCE=worker
      - AUTOSCALER_STEPS=1

  worker:
    x-omnistrate-mode-internal: true
    image: busybox:1.37.0
    command: ['sh', '-c', 'while true; do echo Working...; sleep 10; done']
